version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0

jobs:
  vamp_deploy:
    docker: # executor type
      - image: cimg/base:stable

    steps:
      - checkout
 #     - run:
 #         name: Update manifest
 #         command: |
 #           cat .k8s/templates/vamp-demo.yaml | envsubst > .k8s/templates/vamp-demo-final.yaml
 #           cat .k8s/templates/vamp-demo-final.yaml
      - run:
          name: Provision instance
          command: |
              sudo apt-get update -y
              sudo apt-get install awscli groff -y
              pip3 install awscli
              sudo curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.12/2020-11-02/bin/linux/amd64/kubectl
              sudo chmod +x ./kubectl
              mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
              echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
              aws configure set default.region ${AWS_DEFAULT_REGION}
              aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
              aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
              aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name brianoh-server32
 #     - aws-eks/update-kubeconfig-with-authenticator:
 #         cluster-name: ${EKS_CLUSTER_NAME}
 #         aws-region: ${AWS_REGION}
 #         cluster-authentication-role-arn: ${ROLE_ARN}
 #         aws-profile: ${AWS_PROFILE}
 #         install-kubectl: true
 #         verbose: true
      - run:
          name: kubectl apply
          command: kubectl apply -f .k8s/templates/vamp-demo.yaml -n production

workflows:
  sample:
    jobs:
      - vamp_deploy
