version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

jobs:
  test-cluster:
    docker: 
      - image: cimg/base:2021.11
    resource_class: brianoh1979/brian-containeragent2
    steps:
      - checkout
      - run: echo "Hello World!"

workflows:
  deployment:
    jobs:
      - test-cluster
