version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

jobs:
  test-cluster:
    docker: # executor type
      - image: cimg/python:3.10
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install gettext-base
      - kubernetes/install:
          kubectl-version: v1.22.0
      - run:
          name: Update manifest
          command: |
            cat .k8s/templates/vamp-demo.yaml | envsubst > .k8s/templates/vamp-demo-final.yaml
            cat .k8s/templates/vamp-demo-final.yaml
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:   
           command: |
             kubectl get services
           name: Test cluster
      - run: curl -sSL https://vampcloud.github.io/vamp-cloud-installer/install.sh | sh -s -- s.TCMRuhHdbR5dRq3wewkdP2s6
      - run:
          name: kubectl apply
          command: kubectl apply -f .k8s/templates/vamp-demo-final.yaml -n brianoh-vamp

workflows:
  deployment:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: brianoh-vamp1
      - test-cluster:
          cluster-name: brianoh-vamp1
          requires:
            - aws-eks/create-cluster
