#Comment to trigger commit
version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  test-agent1:
    docker: 
      - image: gcr.io/kaniko-project/executor:v1.9.0-debug
    resource_class: brianoh1979/brian-containeragent2
    
    steps:
      - checkout
      - run:
          name: docker build with kaniko
          command: |
            /kaniko/executor \
             --context $(pwd) \
             --dockerfile Dockerfile \
             --no-push 

workflows:
  deployment:
    jobs:
      - test-agent1
